[PHP]
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
post_max_size = 100M
upload_max_filesize = 100M
max_file_uploads = 50
max_input_vars = 10000
date.timezone = Asia/Jakarta
display_errors = Off
log_errors = On
short_open_tag = Off
realpath_cache_size = 4096K
realpath_cache_ttl = 600
